### ISSUE TITLE
Fallo al instalar módulo account_payment_fix v13

### ISSUE THREAD

**Issue by gstota** [ctmil/odoo-argentina#1]
> *Version affectada:13
> 
>  
> 
> Instalación según instrucciones en:
https://www.moldeointeractive.com.ar/en_US/blog/moldeo-interactive-1/post/instructivo-para-instalacion-de-localizacion-argentina-para-odoo-13-community-741

Indica instalar módulo account_payment_group, el cual depende de account_payment_fix en el __manifest.py

Inicialmente me topé con el error de multi. Esto lo pasé haciendo find . -type f -name '*.py' | xargs sed -i '/@api.multi/d' en la carpeta de los módulos.

> *Lo que pasa actualmente:arroja el siguiente error:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-58>", line 2, in button_immediate_install
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo13/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo13/odoo/odoo/modules/loading.py", line 420, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo13/odoo/odoo/modules/loading.py", line 312, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo13/odoo/odoo/modules/loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "/opt/odoo13/odoo/odoo/modules/registry.py", line 220, in load
    model = cls._build_model(self, cr)
  File "/opt/odoo13/odoo/odoo/models.py", line 521, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)
TypeError: Model 'account.invoice' does not exist in registry.

> *Analisis profunda:*
>
Yo hacer infraestructura, ser manco programando

Googleando encontré que este tipo de errores se debían a dependencias no declaradas, pero a menos que haya cambiado en 13    _inherit = 'account.invoice' debería estar cubierto por el módulo account que está en depends del manifest de account_payment_fix

**Comment by pabarrientos** [comment]
Buenas... como dice el issue problemas al instalar los módulos account_payment_group y account_check ya que me sigue diciendo que tienen dependencia del módulo account_payment_fix que no se encuentra en el repositorio odoo-argentina.

El módulo l10n_ar_afipws_fe ya lo pude instalar sin problemas, el problema que tenía anteriormente era error mio :) ya que ejecutaba el pip3 con sudo y en virtualenv debo hacerlo sin sudo.

Con respecto al plan de cuentas... al parecer se carga automáticamente al instalar l10n_ar, este carga 3 empresas ejemplo con sus respectivos planes de cuenta... RI EX y Mono

Otro problema que noto es que al querer abrir alguna factura de los datos de ejemplo y sólo después de instalar l10n_ar_afipws_fe es el de la imagen
![Captura](https://user-images.githubusercontent.com/14217493/69274618-7d769480-0bb9-11ea-984e-48624aa04bd0.JPG)



Saludos!!

**Comment by morrillo** [comment]
Ahi subi al repositorio de odoo-argentina el modulo account_payment_fix que deberia tener solucionado el tema. En mi maquina lo probe y salio andando bien, pero si quieren probarlo en una instalacion desde cero...

Con respecto al error del vat_taxable_amount, pueden crear otro ticket?
Gracias

**Comment by pabarrientos** [comment]
ok probado en instalación de cero... la instalación de los módulos account_payment_group y account_check se solucionó con el agregado del módulo account_payment_fix al repositorio

**Comment by morrillo** [comment]
Genial, cierro el issue entonces
gracias!
