### ISSUE TITLE
Error al instalar l10n_ar_account_vat_ledger

### ISSUE THREAD

**Issue by juandanielp24** [ctmil/odoo-argentina#11]
> **Error al instalar l10n_ar_account_vat_ledger**

> TypeError: Model 'account.document.type' does not exist in registry.

> *Version affectada:*
> 
>  Odoo 13
> 
> Odoo 13 recién instalado. Se siguieron los pasos del Webinar.
> La FE funciona perfecto.
> Error completo:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/mnt/c/Users/Public/odoo-dev/odoo13/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/mnt/c/Users/Public/odoo-dev/odoo13/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-60>", line 2, in button_immediate_install
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/modules/loading.py", line 191, in load_module_graph
    model_names = registry.load(cr, package)
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/modules/registry.py", line 222, in load
    model = cls._build_model(self, cr)
  File "/mnt/c/Users/Public/odoo-dev/odoo13/odoo/models.py", line 521, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)
TypeError: Model 'account.document.type' does not exist in registry.

**Comment by morrillo** [comment]
Se soluciono al remover el módulo viejo de l10n_ar_account_vat_ledger_citi
