### ISSUE TITLE
Error al validar factura rectificativa

### ISSUE THREAD

**Issue by gpperez** [ctmil/odoo-argentina#12]
> Error al validar factura rectificativa
>
> *Version affectada:*
> 
>  - Odoo 13
> 
> *Pasos para reproducir:*
> 
>  1. Desde una factura -> Agregar factura rectificativa
>  2. Reembolso parcial
>  3. Invertir
>  4. Validar en Homologacion
> *Retorna el error de odoo:*

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/odoo-servers/odoo13/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-servers/odoo13/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo-servers/odoo13/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/odoo-servers/odoo13/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo-servers/odoo13/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-servers/odoo13/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-servers/odoo13/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo-servers/odoo13/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo-servers/odoo13/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-servers/odoo13/odoo/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo-servers/odoo13/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo-servers/odoo13/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo-servers/odoo13/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo-servers/odoo13/addons-demolocarg/odoo-argentina/l10n_ar_afipws_fe/models/move.py", line 236, in action_post
    self.do_pyafipws_request_cae()
  File "/home/odoo/odoo-servers/odoo13/addons-demolocarg/odoo-argentina/l10n_ar_afipws_fe/models/move.py", line 710, in do_pyafipws_request_cae
    afip_ws != 'wsmtxca' and self.date.strftime('%Y%m%d') or self.date.strftime('%Y-%m-%d'),
TypeError: AgregarCmpAsoc() takes from 1 to 5 positional arguments but 6 were given

**Comment by morrillo** [comment]
tenes la versión actualizada de pyafipws? Fijate la definición de la funcion en su repositorio:

    def AgregarCmpAsoc(self, tipo=1, pto_vta=0, nro=0, cuit=None, fecha=None, **kwarg):

y fijate como la estamos llamando, con la cantidad de parametros correctos. Creo que tenes mal actualizado pyafipws
