### ISSUE TITLE
Error al apretar el boton Check Remote/Local Numbers diario Factura Electrónica

### ISSUE THREAD

**Issue by leandrosramirez** [ctmil/odoo-argentina#14]
**Error al apretar el boton Check Remote/Local Numbers  en el apartado de configuración de la factura electrónica**

*Version affectada:*

13.0 

*Pasos para reproducir:*
Despues de crear y configurar el diario de factura electrónica cuando apreto el boton Check Temote / Local Number me tira un error

 *Lo que pasa actualmente:*

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/sources/odoo-argentina/l10n_ar_afipws_fe/models/journal.py", line 97, in check_document_local_remote_number
    for journal_document_type in self.journal_document_type_ids:
AttributeError: 'account.journal' object has no attribute 'journal_document_type_ids'

**Comment by azurita** [comment]
Estoy avanzando con mi implementación y noté el mismo problema. Por ahora, estoy trabajando con un ambiente de homologación y las facturas las genera pero no en secuencia con lo que entrega el ws de afip.

**Comment by mariogustavoorrillo** [comment]
En la versión 14.0 esta resuelto. Basicamente se eliminaron las secuencias. Este es un post donde se habla del tema:

**Comment by mariogustavoorrillo** [comment]
https://www.moldeointeractive.com.ar/blog/moldeo-interactive-1/post/soporte-de-notas-de-credito-y-cambios-en-las-secuencias-988
