### ISSUE TITLE
Error al instalar l10n_ar_afipws_fe

### ISSUE THREAD

**Issue by FranTobar** [ctmil/odoo-argentina#17]
Hola, estoy haciendo mi implementación de Odoo v13 y, al tratar de instalar el l10n_ar_afipws_fe me da el siguiente error. ¿ Existe algún fix ?
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 394, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 987, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
**ValueError: El campo `currency_rate` no existe**

Contexto del error:
**Vista `account.move.afip.form`**
[view_id: 1022, xml_id: n/a, model: account.move, parent_id: 812]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-60>", line 2, in button_immediate_install
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo13/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo13/odoo/odoo/modules/loading.py", line 421, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo13/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo13/odoo/odoo/modules/loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo13/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo13/odoo/odoo/tools/convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo13/odoo/odoo/tools/convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo13/odoo/odoo/tools/convert.py", line 715, in parse
    pycompat.reraise(
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo13/odoo/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/opt/odoo13/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/opt/odoo13/odoo/odoo/tools/convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/opt/odoo13/odoo/odoo/models.py", line 4080, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo13/odoo/odoo/models.py", line 3994, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odoo13/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 475, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo13/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo13/odoo/odoo/models.py", line 3775, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo13/odoo/odoo/fields.py", line 1114, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo13/odoo/odoo/models.py", line 3564, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/opt/odoo13/odoo/odoo/models.py", line 1176, in _validate_fields
    check(self)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 396, in _check_xml
    raise ValidationError("%s\n\n%s" % (_("Error while validating view"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating view

**El campo `currency_rate` no existe

Contexto del error:
Vista `account.move.afip.form`
[view_id: 1022, xml_id: n/a, model: account.move, parent_id: 812]**
None" while parsing /home/nn/odoo13/addons/odoo-argentina/l10n_ar_afipws_fe/views/move_view.xml:2, near
<odoo>
    

    <record id="view_move_form" model="ir.ui.view">
        <field name="model">account.move</field>
        <field name="name">account.move.afip.form</field>
         <field name="inherit_id" ref="l10n_ar.view_move_form"/>
        <field name="arch" type="xml">
            <data>
            <button name="action_post" position="attributes">
                <attribute name="attrs">{'invisible': ['|', ('state', '!=', 'draft'), ('validation_type', '!=', False)]}</attribute>
                <attribute name="states"/>
	    </button>
	    <xpath expr="//form/sheet/div[@name='button_box']" position="before">	
		    <widget name="web_ribbon" title="Homologacion" attrs="{'invisible': [('state', '!=', 'draft'),('validation_type', '!=', 'production')]}"/>
		</xpath>

            <button name="action_post" position="after">
		    <button name="action_post" type="object" attrs="{'invisible': ['|', ('state', '!=', 'draft'), ('validation_type', '!=', 'production')]}" string="Validar en AFIP" class="oe_highlight" groups="account.group_account_invoice"/>
		    <button name="action_post" type="object" attrs="{'invisible': ['|', ('state', '!=', 'draft'), ('validation_type', '!=', 'homologation')]}" string="Validar en HOMOLOGACION" class="oe_highlight" groups="account.group_account_invoice"/>
            </button>

            <field name="l10n_ar_afip_concept" position="after">
		<field name="afip_fce_es_anulacion"/>
	    	<field name="l10n_ar_currency_rate" readonly="1"/>	    
            </field>
            <notebook>
                <page string="AFIP" name="afip">
                    <group>
                        <field name="currency_rate" readonly="1"/>
                        <field name="afip_auth_verify_type" invisible="1"/>
                        <field name="afip_batch_number" invisible="1"/>
                        <field name="validation_type" invisible="1"/>
                        <label for="afip_auth_code" string="AFIP authorization"/>
                        <div class="oe_inline">
                            <field name="afip_auth_mode" class="oe_inline"/>
                            <field name="afip_auth_code" class="oe_inline" attrs="{'required': [('afip_auth_mode', '!=', False)]}" placeholder="Code"/> - 
                            <field name="afip_auth_verify_result" class="oe_inline"/>
                            <button name="verify_on_afip" type="object" attrs="{'invisible': ['|', ('afip_auth_mode', '=', False), ('afip_auth_verify_type', '=', 'not_available')]}" string="Constantar" help="Constatar en AFIP" class="oe_inline oe_link" groups="base.group_user"/>
                        </div>
                        <field name="afip_auth_verify_observation" attrs="{'invisible': [('afip_auth_verify_observation', '=', False)]}"/>
                        <field name="afip_auth_code_due"/>
                        <field name="afip_result"/>
                        <field name="afip_message"/>
                        <field name="afip_xml_request" groups="base.group_no_one"/>
                        <field name="afip_xml_response" groups="base.group_no_one"/>
                    </group>
                </page>
            </notebook>
        </data></field>
    </record>

    
</odoo>

**Comment by micakce** [comment]
```
 <field name="l10n_ar_afip_concept" position="after">
	<field name="afip_fce_es_anulacion"/>
    	<field name="l10n_ar_currency_rate" readonly="1"/>	    
        </field>
        <notebook>
            <page string="AFIP" name="afip">
                <group>
                    <field name="currency_rate" readonly="1"/>
                    <field name="afip_auth_verify_type" invisible="1"/>
                    <field name="afip_batch_number" invisible="1"/>
```

Hola, si, me pasó lo mismo! si te fijas hay uno que dice "currency_rate" y otro que dice "l10n_ar_currency_rate". Yo lo arreglé cambiando ambos a "l10n_ar_currency_rate".

Saludos.

**Comment by vkmc** [comment]
Mismo problema, voy a probar el fix sugerido

**Comment by vkmc** [comment]
Ok, acá [0] lo eliminaron... así que o bien necesitamos ese campo con l10n_ar_currency_rate o bien hay otro problema

[0] https://github.com/ctmil/odoo-argentina/commit/9036fce73f71bfb33c0bc4bce8b8214f9247c88c#diff-3da5a2b65f023bdcb6a52badc1056dcf

**Comment by micakce** [comment]
Analizando un poco el tema diría que no hace falta, si nos fijamos se está extendiendo la vista agregandole un "notebook" y "pages", ya el campo `<field name="l10n_ar_currency_rate" readonly="1"/>` se esta mostrando fuera del notebook, si lo quieres mostrar nuevamente  dentro del `"notebook"` bien, lo puedes repetir. El problema es cuando se usa el `name="currency_rate"`, ya que al estar trabajando con la localización argentina este campo es suplantado por `"l10n_ar_currency_rate"`, y al no encontrarlo en la base de datos revienta el error.

**Comment by mariogustavoorrillo** [comment]
Ya esta resuelto en la versión 14.0
Se cierra el issue.
