### ISSUE TITLE
v13.0 AttributeError: 'account.journal' object has no attribute 'journal_document_type_ids 

### ISSUE THREAD

**Issue by martinllanos** [ctmil/odoo-argentina#19]
**AttributeError: 'account.journal' object has no attribute 'journal_document_type_ids'**

Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo13/odoo/env13/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo13/odoo/env13/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo13/odoo/env13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo13/odoo/env13/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo13/odoo/env13/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo13/odoo/env13/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo13/odoo/env13/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo13/odoo/env13/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/odoo13/odoo/env13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo13/odoo/env13/odoo/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo13/odoo/env13/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo13/odoo/env13/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo13/odoo/env13/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo13/odoo/env13/sources/ctmil-odoo-argentina/l10n_ar_afipws_fe/models/journal.py", line 87, in sync_document_local_remote_number
    for journal_document_type in self.journal_document_type_ids:
AttributeError: 'account.journal' object has no attribute 'journal_document_type_ids'

*Version affectada: 13.0

*Pasos para reproducir:*

1. Prueba Dummy Test

![imagen](https://user-images.githubusercontent.com/463008/84084908-cc034900-a9ba-11ea-841f-ec95744bd922.png)

2. Prueba Sync Remote/Local Numbers

![imagen](https://user-images.githubusercontent.com/463008/84085033-1684c580-a9bb-11ea-87cf-e6c410bd96c8.png)

*Lo que debe pasar:*

Me tendria que dar el OK de sincronización

**Comment by morrillo** [comment]
Ya fue solucionado

**Comment by regaby** [comment]
@morrillo estoy teniendo el mismo error, bajé los últimos cambios del repositorio
![image](https://user-images.githubusercontent.com/8516488/96187460-6cdab580-0f13-11eb-8693-91b0f74215bf.png)

**Comment by cebas** [comment]
@morrillo tengo exactamente el mismo error. acabo de bajar la última version
