### ISSUE TITLE
Error installing module l10n_ar_afipws_fe in branch 14.0

### ISSUE THREAD

**Issue by pauletti** [ctmil/odoo-argentina#35]
- Yo creo que es relacionado al parsing del siguiente xml

 /opt/odoo/odoo-14/sources/odoo-argentina/account_move_tax/views/move_view.xml:4

Field type used in attrs.invisible ({'invisible': [('type','=','entry')]}) must be present in view but is missing.

View name: account.move.afip.form
Error context:
view: ir.ui.view(833,)
xmlid: view_move_form
view.model: account.move
view.parent: ir.ui.view(589,)
file: /opt/odoo/odoo-14/sources/odoo-argentina/account_move_tax/views/move_view.xml

-  reporte completo del error

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo-14/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/opt/odoo/odoo-14/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/opt/odoo/odoo-14/odoo/models.py", line 4203, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo/odoo-14/odoo/models.py", line 4132, in _load_records_create
    return self.create(values)
  File "<decorator-gen-43>", line 2, in create
  File "/opt/odoo/odoo-14/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo-14/odoo/addons/base/models/ir_ui_view.py", line 482, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-65>", line 2, in create
  File "/opt/odoo/odoo-14/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo-14/odoo/addons/base/models/ir_fields.py", line 533, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/opt/odoo/odoo-14/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo-14/odoo/models.py", line 3893, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo/odoo-14/odoo/fields.py", line 1147, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo-14/odoo/addons/base/models/ir_ui_view.py", line 300, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo-14/odoo/addons/base/models/ir_ui_view.py", line 500, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo-14/odoo/models.py", line 3682, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/opt/odoo/odoo-14/odoo/models.py", line 1250, in _validate_fields
    check(self)
  File "/opt/odoo/odoo-14/odoo/addons/base/models/ir_ui_view.py", line 408, in _check_xml
    raise ValidationError(_(
  File "/opt/odoo/odoo-14/odoo/addons/base/models/ir_ui_view.py", line 391, in _check_xml
    view.postprocess_and_fields(view_doc, validate=True)
  File "/opt/odoo/odoo-14/odoo/addons/base/models/ir_ui_view.py", line 851, in postprocess_and_fields
    arch, name_manager = self._postprocess_view(node, model, validate=validate)
  File "/opt/odoo/odoo-14/odoo/addons/base/models/ir_ui_view.py", line 865, in _postprocess_view
    name_manager.check_view_fields(self)
  File "/opt/odoo/odoo-14/odoo/addons/base/models/ir_ui_view.py", line 1991, in check_view_fields
    view.handle_view_error(msg)
  File "/opt/odoo/odoo-14/odoo/addons/base/models/ir_ui_view.py", line 673, in handle_view_error
    raise ValueError(formatted_message).with_traceback(from_traceback) from from_exception
odoo.exceptions.ValidationError: Error while validating view:

Field type used in attrs.invisible ({'invisible': [('type','=','entry')]}) must be present in view but is missing.

View name: account.move.afip.form
Error context:
 view: ir.ui.view(833,)
 xmlid: view_move_form
 view.model: account.move
 view.parent: ir.ui.view(589,)
 file: /opt/odoo/odoo-14/sources/odoo-argentina/account_move_tax/views/move_view.xml

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo-14/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo-14/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-14/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-14/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-14/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-14/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-14/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-14/addons/web/controllers/main.py", line 1381, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-14/addons/web/controllers/main.py", line 1369, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-14/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-14/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "/opt/odoo/odoo-14/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo-14/odoo/addons/base/models/ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo-14/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo-14/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-14/odoo/modules/loading.py", line 453, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/odoo-14/odoo/modules/loading.py", line 346, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/odoo-14/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/opt/odoo/odoo-14/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/opt/odoo/odoo-14/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/opt/odoo/odoo-14/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo/odoo-14/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/opt/odoo/odoo-14/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo-14/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-14/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /opt/odoo/odoo-14/sources/odoo-argentina/account_move_tax/views/move_view.xml:4, near
<record id="view_move_form" model="ir.ui.view">
        <field name="model">account.move</field>
        <field name="name">account.move.afip.form</field>
        <field name="inherit_id" ref="account.view_move_form"/>
	<field name="arch" type="xml">
		<data><field name="state" position="before">
			<button name="compute_taxes" type="object" string="Computar Impuestos" states="draft"/>
		</field>
		<field name="line_ids" position="after">
			<field name="move_tax_ids" readonly="1" attrs="{'invisible': [('type','=','entry')]}">
				<tree>
					<field name="move_id"/>
					<field name="tax_id"/>
					<field name="base_amount"/>
					<field name="tax_amount"/>
				</tree>
			</field>
			<group string="Montos agrupados de impuestos">
				<field name="vat_taxable_amount"/>
				<field name="vat_amount"/>
				<field name="other_taxes_amount"/>
				<field name="vat_untaxed_base_amount"/>
			</group>
		</field>
	</data></field>
    </record>

**Comment by mariogustavoorrillo** [comment]
Ya se solucionó. Hace un nuevo pull y proba otra vez.
