### ISSUE TITLE
sync_document_local_remote_number

### ISSUE THREAD

**Issue by nahe-consulting-group** [ctmil/odoo-argentina#38]
Me salto un error al sincronizar números locales y remotos del diario de facturas electrónicas en homologación.

para odoo 13
File "/opt/odoo13/odoo/repositorios/moldeo-odoo-argentina/l10n_ar_afipws_fe/models/journal.py", line 87, in sync_document_local_remote_number
    for journal_document_type in self.journal_document_type_ids:
AttributeError: 'account.journal' object has no attribute 'journal_document_type_ids'

> *Pasos para reproducir:*
> 
>  1. crear diario con el mismo certificado de homologación que ya tenía en otro lado
>  2. hacer click en sincronizar los numeros locales con remotos
>  3. leer el error :) 

Para ayudar, hoy mismo mas temprano con el repo de odoo-argentina de adhoc este error no pasaba, probablemente puedan buscar ahi la diferencia en el código. 

Gracias por todo

**Comment by FedericoLaTorre** [comment]
Estoy con el mismo error:
Ubuntu 20.04

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1343, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/sources/odoo-argentina/l10n_ar_afipws_fe/models/journal.py", line 87, in sync_document_local_remote_number
    for journal_document_type in self.journal_document_type_ids:
AttributeError: 'account.journal' object has no attribute 'journal_document_type_ids'

**Comment by mariogustavoorrillo** [comment]
Resuelto en la versión 14

https://www.moldeointeractive.com.ar/blog/moldeo-interactive-1/post/soporte-de-notas-de-credito-y-cambios-en-las-secuencias-988
