### ISSUE TITLE
Error Conexión AFIP Facturación Electrónica V13

### ISSUE THREAD

**Issue by pabarrientos** [ctmil/odoo-argentina#4]
Una vez configurados los certificados para la conexión con los webservices de afip (en homologación). Se procede a configurar el diario para un punto de venta electrónico... al pulsar sobre get connection o dummy test u otro botón se obtiene el siguiente error

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/odoo/13/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/13/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo/13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/odoo/13/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo/13/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo/13/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo/13/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo/13/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo/13/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/13/odoo/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo/13/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo/13/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo/13/odoo/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo/13/sources/odoo-argentina/l10n_ar_afipws_fe/models/journal.py", line 217, in action_get_connection
    self.company_id.get_connection(afip_ws).connect()
  File "/home/odoo/odoo/13/sources/odoo-argentina/l10n_ar_afipws/models/res_company.py", line 136, in get_connection
    connection = self._create_connection(afip_ws, environment_type)
  File "/home/odoo/odoo/13/sources/odoo-argentina/l10n_ar_afipws/models/res_company.py", line 163, in _create_connection
    return self.connection_ids.create(auth_data)
  File "<decorator-gen-3>", line 2, in create
  File "/home/odoo/odoo/13/odoo/odoo/api.py", line 343, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/odoo/13/odoo/odoo/models.py", line 3707, in create
    records = self._create(data_list)
  File "/home/odoo/odoo/13/odoo/odoo/models.py", line 3824, in _create
    cache_value = field.convert_to_cache(value, record)
  File "/home/odoo/odoo/13/odoo/odoo/fields.py", line 1756, in convert_to_cache
    return self.to_datetime(value)
  File "/home/odoo/odoo/13/odoo/odoo/fields.py", line 1736, in to_datetime
    return datetime.strptime(value, DATETIME_FORMAT[:len(value)-2])
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2019-11-22T18:03:43.709-03:00' does not match format '%Y-%m-%d %H:%M:%S'

Versión afectada: 13

Saludos!!!

**Comment by pabarrientos** [comment]
Ya no dá este error... gracias!!!
