### ISSUE TITLE
Error configuracion diario pv factura electronica v13

### ISSUE THREAD

**Issue by pabarrientos** [ctmil/odoo-argentina#5]
> **Error configuracion diario pv factura electronica v13**
>
> *Versión afectada:*
> 
>  - 13.0
> 
> *Pasos para reproducir:*
> 
>  Cuando se crea o edita un diario de tipo venta para factura electrónica, al hacer click en los siguientes botones:
>  - Check Remote/Local Numbers
>  - Sync Remote/Local Numbers
> 
> *Lo que pasa actualmente:*
> 
>  Arroja el siguiente error:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/odoo/13/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/13/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo/13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/odoo/13/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo/13/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo/13/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo/13/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo/13/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo/13/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/13/odoo/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo/13/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo/13/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo/13/odoo/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo/13/sources/odoo-argentina/l10n_ar_afipws_fe/models/journal.py", line 97, in check_document_local_remote_number
    for journal_document_type in self.journal_document_type_ids:
AttributeError: 'account.journal' object has no attribute 'journal_document_type_ids' 
```

**Comment by morrillo** [comment]
Ya fue solucionado

**Comment by cebas** [comment]
@morrillo me pasa lo mismo, usando la última versión
