### ISSUE TITLE
Error installing  Listado de Bancos Argentinos (l10n_ar_bank)

### ISSUE THREAD

**Issue by MatiasJAco** [ctmil/odoo-argentina#55]
Al instalar el modulo Listado de Bancos Argentinos (l10n_ar_bank) del branch 15.0  en una instalacion nueva  nos da el siguiente error:
Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/opt/odoo15/odoo/odoo/tools/convert.py", line 583, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/opt/odoo15/odoo/odoo/models.py", line 4417, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo15/odoo/odoo/models.py", line 4338, in _load_records_create
    return self.create(values)
  File "<decorator-gen-42>", line 2, in create
  File "/opt/odoo15/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_ui_view.py", line 539, in create
    result = super(View, self.with_context(ir_ui_view_partial_validation=True)).create(vals_list)
  File "<decorator-gen-67>", line 2, in create
  File "/opt/odoo15/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_fields.py", line 613, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/opt/odoo15/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo15/odoo/odoo/models.py", line 4070, in create
    records = self._create(data_list)
  File "/opt/odoo15/odoo/odoo/models.py", line 4235, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/opt/odoo15/odoo/odoo/models.py", line 1367, in _validate_fields
    check(self)
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_ui_view.py", line 460, in _check_xml
    raise err.with_traceback(e.__traceback__) from None
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_ui_view.py", line 434, in _check_xml
    view._validate_view(combined_arch, view.model)
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_ui_view.py", line 1292, in _validate_view
    validator(node, name_manager, node_info)
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_ui_view.py", line 1401, in _validate_tag_field
    self._raise_view_error(msg, node)
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_ui_view.py", line 739, in _raise_view_error
    raise err from from_exception
odoo.exceptions.ValidationError: Ocurrió un error al validar vista cercana

<form string="Bank account">
                <sheet>
                    <widget name="web_ribbon" title="Archived" bg_color="bg-danger" attrs="{'invisible': [('active', '=', True)]}"/>
                    <group>
                        <group>

El campo "cbu" no existe en el modelo "res.partner.bank"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo15/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo15/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo15/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo15/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo15/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo15/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo15/odoo/addons/web/controllers/main.py", line 1351, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo15/odoo/addons/web/controllers/main.py", line 1339, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo15/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo15/odoo/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_module.py", line 483, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_module.py", line 600, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo15/odoo/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo15/odoo/odoo/modules/loading.py", line 474, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo15/odoo/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo15/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/opt/odoo15/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/opt/odoo15/odoo/odoo/tools/convert.py", line 745, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/opt/odoo15/odoo/odoo/tools/convert.py", line 811, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo15/odoo/odoo/tools/convert.py", line 731, in parse
    self._tag_root(de)
  File "/opt/odoo15/odoo/odoo/tools/convert.py", line 691, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo15/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /opt/odoo15/custom-addons/l10n_ar_bank/l10n_ar_bank.xml:15
Ocurrió un error al validar vista cercana

<form string="Bank account">
                <sheet>
                    <widget name="web_ribbon" title="Archived" bg_color="bg-danger" attrs="{'invisible': [('active', '=', True)]}"/>
                    <group>
                        <group>

El campo "cbu" no existe en el modelo "res.partner.bank"

View error context:
{'file': '/opt/odoo15/custom-addons/l10n_ar_bank/l10n_ar_bank.xml',
 'line': 3,
 'name': 'res.bank.form',
 'view': ir.ui.view(796,),
 'view.model': 'res.partner.bank',
 'view.parent': ir.ui.view(141,),
 'xmlid': 'view__bank_form'}

**Comment by mariogustavoorrillo** [comment]
No lo pude reproducir localmente. Seguro tenes un problema con la instalación, por algun motivo directamente no crea el campo cbu en la base de datos. Es muy probable que haya un módulo que cancela la instalación y no te de mensaje de error.

**Comment by mariogustavoorrillo** [comment]
igual mandame un mail a gustavo.orrillo@moldeointeractive.com.ar, porque tenes un problema con la instalación que va más alla del módulo
