### ISSUE TITLE
Error la instalar el modulo l10n_ar_afipws_fe

### ISSUE THREAD

**Issue by Maurix09** [ctmil/odoo-argentina#58]
> **Error la instalar el modulo l10n_ar_afipws_fe**
>
> *Version affectada:*
> 
>  - 16.0 comunidad + Linux Server 20.0 (ubuntu)
> 
> *Pasos para reproducir:*
> 
>  1. Instalo Linux server desde cero.
>  2. clono el repositorio odoo-argentina (git clone --branch 16.0 xxxxxx...........)
>  3. Instalo os requerimientos (pip3 install -t requirements.txt)
>  4. chown www-data -R /usr/local/lib/python3.8/dist-packages/pyafipws
         chmod a+xr -R /usr/local/lib/python3.8/dist-packages/pyafipws
         mkdir usr/local/lib/python3.9/dist-packages/pyafipws/cache 
         chmod a+xwrt -R /usr/local/lib/python3.8/dist-packages/pyafipws/cache
 
       La version 3.8 de Phyton es la que aparece en la carpeta usr/local/lib/
> 5. Instalo el modulo l10n_ar_afipws sin problemas.

> *Lo que pasa actualmente:*
> 
**>  Error al instalar el modulo l10n_ar_afipws_fe**
> 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1579, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1608, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1805, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 144, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 491, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 615, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 91, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 482, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 371, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 206, in load_module_graph
    registry.setup_models(cr)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 285, in setup_models
    model._setup_base()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2769, in _setup_base
    self._add_field(name, fields_[-1].new(_base_fields=fields_))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 584, in _add_field
    field.__set_name__(cls, name)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 383, in __set_name__
    self._setup_attrs(owner, name)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2606, in _setup_attrs
    ondelete.setdefault(key, 'set null')
AttributeError: 'str' object has no attribute 'setdefault'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@http://192.168.10.8:8069/web/assets/187-50b93b4/web.assets_backend.min.js:963:274
    makeErrorFromResponse@http://192.168.10.8:8069/web/assets/187-50b93b4/web.assets_backend.min.js:967:163
    jsonrpc/promise</<@http://192.168.10.8:8069/web/assets/187-50b93b4/web.assets_backend.min.js:974:34

**Comment by mariogustavoorrillo** [comment]
ahi tenes otra historia... es raro...
estoy siguiendo el proyecto aca

https://github.com/a2systems/odoo-argentina

hace un clon y arranca con una base de datos nueva
y de paso reinicia el Odoo
