### ISSUE TITLE
Error al Imprimir factura electrónica 

### ISSUE THREAD

**Issue by walterwor** [ctmil/odoo-argentina#62]
> **No me gusta mi camisa**
>
> *Versión afectada:*
> 
>  - 16.0 y encima
> 
> *Pasos para reproducir:*
> 
>  1. ingresar a facturación/contabilidad
>  2. crear factura
>  3. imprimir - facturas electrónicas
> 
> *Lo que pasa actualmente:*
> 
>  - Al intentar imprimir una factura desde la opción facturación electrónica tengo el siguiente error: 
```
RPC_ERROR

Odoo Server Error

Traceback (most recent call last):
  File "<819>", line 1995, in template_819
  File "<819>", line 301, in template_819_content
AttributeError: 'account.move' object has no attribute 'type'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/report.py", line 113, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/report.py", line 42, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(reportname, docids, data=data)[0]
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/ir_actions_report.py", line 58, in _render_qweb_pdf
    return super()._render_qweb_pdf(report_ref, res_ids=res_ids, data=data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 819, in _render_qweb_pdf
    collected_streams = self._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/usr/lib/python3/dist-packages/odoo/addons/account_edi_ubl_cii/models/ir_actions_report.py", line 58, in _render_qweb_pdf_prepare_streams
    collected_streams = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/usr/lib/python3/dist-packages/odoo/addons/account_edi/models/ir_actions_report.py", line 14, in _render_qweb_pdf_prepare_streams
    collected_streams = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/ir_actions_report.py", line 20, in _render_qweb_pdf_prepare_streams
    return super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 708, in _render_qweb_pdf_prepare_streams
    html = self.with_context(**additional_context)._render_qweb_html(report_ref, res_ids_wo_stream, data=data)[0]
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 896, in _render_qweb_html
    return self._render_template(report.report_name, data), 'html'
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 623, in _render_template
    return view_obj._render_template(template, values).encode()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 2125, in _render_template
    return self.env['ir.qweb']._render(template, values)
  File "/usr/lib/python3/dist-packages/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 580, in _render
    result = ''.join(rendering)
  File "<820>", line 80, in template_820
  File "<820>", line 62, in template_820_content
  File "<820>", line 50, in template_820_t_call_0
  File "<819>", line 2001, in template_819
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
AttributeError: 'account.move' object has no attribute 'type'
Template: l10n_ar_report_fe.report_fe_invoice_document
Path: /t/div/div[1]/div[2]/div[1]
Node: <div class="col-8" t-if="o.type == \'out_invoice\' and (o.state == \'posted\') and o.l10n_ar_afip_service_start and o.l10n_ar_afip_service_end"/>

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@https://doncoco.consultoresinformaticos.com.ar/web/assets/82782-80c1637/web.assets_backend.min.js:982:274
    makeErrorFromResponse@https://doncoco.consultoresinformaticos.com.ar/web/assets/82782-80c1637/web.assets_backend.min.js:986:163
    download._download/</xhr.onload/decoder.onload@https://doncoco.consultoresinformaticos.com.ar/web/assets/82782-80c1637/web.assets_backend.min.js:974:7
```
>  - Ya actualice los módulos relacionados a afip, afip_fe, report_fe, podrán darme una mano por favor. Gracias

**Comment by mariogustavoorrillo** [comment]
Walter, cierro el ticket porque estamos manteniendo la version 16 en otro lado. 
Fijate este post donde tenes las instrucciones sobre como instalarla y los datos del nuevo repositorio

https://a2systems.co/blog/blog-2/instalacion-de-la-localizacion-argentina-odoo16-5

cualquier cosa mandame un mail a gustavo@a2systems.co
